name: CI
# This was forked from a file written by (@oscgonfer) on Nov. 7th, 2023 (the history was lost)
on:
  pull_request:
    branches:
    - master
    paths-ignore:
    - hardware/**
  push:
    branches:
    - master
    paths-ignore:
    - hardware/**

jobs:
  # This is was first written by Raz Tamim (@raztam) on Aug. 12th, 2025 (the history was lost)
  clang_checks:
    name: Clang Format & Tidy
    runs-on: ubuntu-latest

    steps:
      - name: Check out the commit
        uses: actions/checkout@v3
        with:
          submodules: 'false'

      - name: Build clang checks Docker image
        run: docker build -t daphi-clang-checks guidelines_checks

      - name: Get changed files
        id: changed
        run: |
          git fetch --unshallow || true
          git fetch origin ${{ github.base_ref }}
          git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -E '^esp/src/.*\.(cpp|h|ino)$' > changed-files.txt || true

      - name: Run clang-format (auto-format changed files)
        run: |
          if [ -s changed-files.txt ]; then
            docker run --rm -v "$PWD":/workspace -w /workspace daphi-clang-checks \
              sh -c 'clang-format -i $(cat changed-files.txt)'
          else
            echo "No changed source files to format."
          fi
              
      - name: Run clang-tidy checks on changed files
        run: |
          if [ -s changed-files.txt ]; then
            docker run --rm -v "$PWD":/workspace -w /workspace daphi-clang-checks \
              sh /workspace/guidelines_checks/run-clang-checks.sh $(cat changed-files.txt)
          else
            echo "No changed source files to check."
          fi
